name: docker_publish

on:
  pull_request:
    branches:
    - 'feat/babylon-rfc'

jobs:
  docker_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push to Docker Hub
        id: build-dockerhub
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./ops/docker/op-stack-go/Dockerfile
          target: op-node-target
          outputs: type=image,name=${{ vars.DOCKERHUB_REGISTRY_ID }}/op-node-babylon-finality-gadget:${{ steps.get_version.outputs.VERSION }},push=true

